<?php
/**
 * TL_ROOT/system/modules/calendar_editor/languages/de/modules.php 
 * 
 * Contao extension: calendar_editor 1.2.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Daniel Gaußmann 
 * License   : LGPL 
 * Author    : Daniel Gaußmann (gausi), http://www.gausi.de 
 * Translator: Daniel Gaußmann (gausi), http://www.gausi.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FMD']['calendarEdit']['0'] = "Kalender mit FE Bearbeitung";
$GLOBALS['TL_LANG']['FMD']['calendarEdit']['1'] = "Fügt der Seite einen Kalender mit zusätzlichen Links zur Frontend-Bearbeitung hinzu.";
$GLOBALS['TL_LANG']['FMD']['EventEditor']['0'] = "Event-Editor";
$GLOBALS['TL_LANG']['FMD']['EventEditor']['1'] = "Fügt der Seite ein Formular hinzu zur Bearbeitung von Terminen.";
$GLOBALS['TL_LANG']['FMD']['EventReaderEditLink']['0'] = "Eventleser: Edit-link";
$GLOBALS['TL_LANG']['FMD']['EventReaderEditLink']['1'] = "Fügt der Seite einen Link hinzu auf die Seite mit dem passenden Event-Editor.";
$GLOBALS['TL_LANG']['FMD']['EventHiddenList']['0'] = "Unveröffentlichte Eventliste";
$GLOBALS['TL_LANG']['FMD']['EventHiddenList']['1'] = "Fügt der Seite eine Liste mit unveröffentlichten(!) Terminen hinzu.";
 
?>
