<?php
/**
 * TL_ROOT/system/modules/calendar_editor/languages/de/tl_calendar_events.php 
 * 
 * Contao extension: calendar_editor 1.2.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Daniel Gaußmann 
 * License   : LGPL 
 * Author    : Daniel Gaußmann (gausi), http://www.gausi.de 
 * Translator: Daniel Gaußmann (gausi), http://www.gausi.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_calendar_events']['FE_User']['0'] = "Frontend Autor";
$GLOBALS['TL_LANG']['tl_calendar_events']['FE_User']['1'] = "Der Frontend-Benutzer, der diesen Termin erstellt hat.";
$GLOBALS['TL_LANG']['tl_calendar_events']['disable_editing']['0'] = "Frontend-Bearbeitung sperren";
$GLOBALS['TL_LANG']['tl_calendar_events']['disable_editing']['1'] = "Wenn dies aktiviert ist, kann dieser Termin nicht mehr im Frontend bearbeitet werden. Auch nicht von den Frontend-Administratoren.";
$GLOBALS['TL_LANG']['tl_calendar_events']['edit_legend'] = "Bearbeitung im Frontend";
 
?>
