<?php
/**
 * TL_ROOT/system/modules/calendar_editor/languages/de/tl_module.php 
 * 
 * Contao extension: calendar_editor 1.2.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Daniel Gaußmann 
 * License   : LGPL 
 * Author    : Daniel Gaußmann (gausi), http://www.gausi.de 
 * Translator: Daniel Gaußmann (gausi), http://www.gausi.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['caledit_add_jumpTo']['0'] = "Weiterleitungsseite zum Hinzufügen von Terminen";
$GLOBALS['TL_LANG']['tl_module']['caledit_add_jumpTo']['1'] = "Bitte wählen Sie die Seite aus, auf die der Nutzer bei Klick auf einen \"Termin hinzufügen\"-Link weitergeleitet wird.";

$GLOBALS['TL_LANG']['tl_module']['caledit_template']['0'] = "Event-Editor Template (bearbeiten)";
$GLOBALS['TL_LANG']['tl_module']['caledit_template']['1'] = "Wählen Sie das Template für den Event-Editor, wenn Sie ein Event bearbeiten wollen.";

$GLOBALS['TL_LANG']['tl_module']['caledit_delete_template']['0'] = "Event-Editor Template (löschen)";
$GLOBALS['TL_LANG']['tl_module']['caledit_delete_template']['1'] = "Wählen Sie das Template für den Event-Editor, wenn Sie ein Event löschen wollen.";

$GLOBALS['TL_LANG']['tl_module']['caledit_clone_template']['0'] = "Event-Editor Template (duplizieren)";
$GLOBALS['TL_LANG']['tl_module']['caledit_clone_template']['1'] = "Wählen Sie das Template für den Event-Editor, wenn Sie ein Event duplizieren wollen.";

$GLOBALS['TL_LANG']['tl_module']['caledit_showCloneLink']['0'] = "Füge einen 'Duplizieren'-Link hinzu.";
$GLOBALS['TL_LANG']['tl_module']['caledit_showCloneLink']['1'] = "Erzeugt einen zuätzlichen Link, um das Event zu duplizieren.";

$GLOBALS['TL_LANG']['tl_module']['caledit_showDeleteLink']['0'] = "Füge einen 'Löschen'-Link hinzu.";
$GLOBALS['TL_LANG']['tl_module']['caledit_showDeleteLink']['1'] = "Erzeugt einen zuätzlichen Link, um das Event zu löschen.";

$GLOBALS['TL_LANG']['tl_module']['caledit_tinMCEtemplate']['0'] = "Richtext Editor";
$GLOBALS['TL_LANG']['tl_module']['caledit_tinMCEtemplate']['1'] = "Wählen Sie eine Konfigurations-Datei, falls Sie den TinyMCE Richtext-Editor verwenden möchten. Sie können weitere Konfigurationen durch Hinzufügen einer Datei \"tinyXXX\" im Ordner system/config.";
$GLOBALS['TL_LANG']['tl_module']['caledit_allowPublish']['0'] = "Veröffentlichung erlauben";
$GLOBALS['TL_LANG']['tl_module']['caledit_allowPublish']['1'] = "Wenn dies aktiviert ist, können die Frontend-User ihre eingetragenen Termine selbst veröffentlichen. Ansonsten muss das ein Backend-User erledigen.";
$GLOBALS['TL_LANG']['tl_module']['caledit_allowDelete']['0'] = "Löschen erlauben";
$GLOBALS['TL_LANG']['tl_module']['caledit_allowDelete']['1'] = "Wenn dies aktiviert ist, kann der Frontend-User die Events komplett aus der Datenbank löschen.";
$GLOBALS['TL_LANG']['tl_module']['caledit_sendMail']['0'] = "E-Mail-Benachrichtigung senden";
$GLOBALS['TL_LANG']['tl_module']['caledit_sendMail']['1'] = "Sendet eine Benachrichtigungs-E-Mail, wenn ein neuer Termin erstellt, oder ein vorhandener bearbeitet wird.";
$GLOBALS['TL_LANG']['tl_module']['caledit_mailRecipient']['0'] = "E-Mail Empfänger";
$GLOBALS['TL_LANG']['tl_module']['caledit_mailRecipient']['1'] = "Geben Sie die E-Mail-Adresse an, an die die Benachrichtigung geschickt werden soll. Sie können auch mehrere Adressen durch Kommata getrennt angeben.";
$GLOBALS['TL_LANG']['tl_module']['caledit_alternateCSSLabel']['0'] = "Bezeichnung für das Feld \"CSS-Klasse\"";
$GLOBALS['TL_LANG']['tl_module']['caledit_alternateCSSLabel']['1'] = "Geben Sie eine alternative Bezeichnung für das Feld \"CSS-Klasse\" an (z.B. \"Ort\", oder \"Trainer\").";
$GLOBALS['TL_LANG']['tl_module']['caledit_mandatoryfields']['0'] = "Weitere Pflichtfelder";
$GLOBALS['TL_LANG']['tl_module']['caledit_mandatoryfields']['1'] = "Geben Sie an, welche Felder ausgefüllt werden müssen. Die Felder \"Startdatum\" and \"Titel\" sind IMMER Pflichtfelder.";
$GLOBALS['TL_LANG']['tl_module']['caledit_usePredefinedCss']['0'] = "Vordefinierte CSS-Werte benutzen";
$GLOBALS['TL_LANG']['tl_module']['caledit_usePredefinedCss']['1'] = "geben Sie einige CSS-Klassen an, aus denen die Frontend-User wählen können.";
$GLOBALS['TL_LANG']['tl_module']['caledit_cssValues']['0'] = "CSS Bezeichner/Werte";
$GLOBALS['TL_LANG']['tl_module']['caledit_cssValues']['1'] = "Geben Sie eine Liste von Bezeichnern/Wert für CSS-Klassen an. Der \"Bezeichner\" wird in der Auswahl angezeigt, der \"Wert\" wird als CSS-Klasse benutzt.";
$GLOBALS['TL_LANG']['tl_module']['edit_legend'] = "Bearbeitung im Frontend";
$GLOBALS['TL_LANG']['tl_module']['css_label'] = "Bezeichner";
$GLOBALS['TL_LANG']['tl_module']['css_value'] = "Wert";
$GLOBALS['TL_LANG']['tl_caledit_mandatoryfields']['starttime'] = "Startzeit";
$GLOBALS['TL_LANG']['tl_caledit_mandatoryfields']['location'] = "Veranstaltungsort";
$GLOBALS['TL_LANG']['tl_caledit_mandatoryfields']['teaser'] = "Teaser";
$GLOBALS['TL_LANG']['tl_caledit_mandatoryfields']['details'] = "Details";
$GLOBALS['TL_LANG']['tl_caledit_mandatoryfields']['css'] = "CSS-Klasse";
$GLOBALS['TL_LANG']['tl_module']['caledit_allowClone']['0'] = "Klonen erlauben";
$GLOBALS['TL_LANG']['tl_module']['caledit_allowClone']['1'] = "Wenn dies aktiviert ist, kann der Frontend-User ein Events klonen und dadurch schneller gleichartige Events an unterschiedlichen Tagen erstellen.";

$GLOBALS['TL_LANG']['tl_module']['edit_holidays'] = "Ferienkalender";
$GLOBALS['TL_LANG']['tl_module']['caledit_holidayCalendar']['0'] = "Kalender mit Hinweisen zu Ferien und Feiertagen";
$GLOBALS['TL_LANG']['tl_module']['caledit_holidayCalendar']['1'] = "Geben Sie den Kalender mit Terminen an, die als Feiertagshinweise im Kalender direkt beim Wochentag ausgegeben werden. Hinweis: Dieser muss auch oben bei 'Kalender' angewählt sein.";
 
 
?>
